# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\tdiplomski\"\xaf\x01\n\x04User\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x10\n\x08username\x18\x02 \x02(\t\x12\r\n\x05\x65mail\x18\x03 \x02(\t\x12\x0e\n\x06joined\x18\x04 \x02(\t\x12&\n\x06gender\x18\x05 \x02(\x0e\x32\x16.diplomski.User.Gender\x12\x10\n\x08location\x18\x06 \x02(\t\x12\x10\n\x08\x62irthday\x18\x07 \x02(\t\"\x1e\n\x06Gender\x12\x08\n\x04MALE\x10\x00\x12\n\n\x06\x46\x45MALE\x10\x01\"*\n\x08UserList\x12\x1e\n\x05users\x18\x01 \x03(\x0b\x32\x0f.diplomski.User')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=26
  _globals['_USER']._serialized_end=201
  _globals['_USER_GENDER']._serialized_start=171
  _globals['_USER_GENDER']._serialized_end=201
  _globals['_USERLIST']._serialized_start=203
  _globals['_USERLIST']._serialized_end=245
# @@protoc_insertion_point(module_scope)
