# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: newaddressbook.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'newaddressbook.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14newaddressbook.proto\x12\x08tutorial\"\xb8\x02\n\tNewPerson\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x32\n\x06phones\x18\x04 \x03(\x0b\x32\".tutorial.NewPerson.NewPhoneNumber\x1a\x61\n\x0eNewPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12?\n\x04type\x18\x02 \x01(\x0e\x32 .tutorial.NewPerson.NewPhoneType:\x0fPHONE_TYPE_HOME\"k\n\x0cNewPhoneType\x12\x1a\n\x16PHONE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11PHONE_TYPE_MOBILE\x10\x01\x12\x13\n\x0fPHONE_TYPE_HOME\x10\x02\x12\x13\n\x0fPHONE_TYPE_WORK\x10\x03\"A\n\x0eNewAddressBook\x12\n\n\x02id\x18\x01 \x01(\x05\x12#\n\x06people\x18\x02 \x03(\x0b\x32\x13.tutorial.NewPerson')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'newaddressbook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEWPERSON']._serialized_start=35
  _globals['_NEWPERSON']._serialized_end=347
  _globals['_NEWPERSON_NEWPHONENUMBER']._serialized_start=141
  _globals['_NEWPERSON_NEWPHONENUMBER']._serialized_end=238
  _globals['_NEWPERSON_NEWPHONETYPE']._serialized_start=240
  _globals['_NEWPERSON_NEWPHONETYPE']._serialized_end=347
  _globals['_NEWADDRESSBOOK']._serialized_start=349
  _globals['_NEWADDRESSBOOK']._serialized_end=414
# @@protoc_insertion_point(module_scope)
